// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cplzhtfuhrwvomxykjbf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNwbHpodGZ1aHJ3dm9teHlramJmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE5MDEzMDAsImV4cCI6MjA1NzQ3NzMwMH0.ZeBQ_EX0nyNlT21RjVKEgxhiN4dqrS3q3nvyUUxdqhQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);